CREATE TABLE IF NOT EXISTS google_ads_property_leads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  budget VARCHAR(50) NOT NULL,
  locations LONGTEXT NOT NULL,
  gclid VARCHAR(255) NULL,
  gbraid VARCHAR(255) NULL,
  wbraid VARCHAR(255) NULL,
  utm_source VARCHAR(255) NULL,
  utm_medium VARCHAR(255) NULL,
  utm_campaign VARCHAR(500) NULL,
  utm_term VARCHAR(500) NULL,
  utm_content VARCHAR(500) NULL,
  landing_page TEXT NULL,
  referrer TEXT NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  whatsapp_clicked TINYINT(1) NOT NULL DEFAULT 0,
  whatsapp_clicked_at TIMESTAMP NULL DEFAULT NULL,
  whatsapp_update_token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  PRIMARY KEY (id),
  KEY idx_google_ads_leads_submitted_at (submitted_at),
  KEY idx_google_ads_leads_phone (phone),
  KEY idx_google_ads_leads_gclid (gclid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
